## AXVU13P 开发板引脚约束
## 引脚来源：AXVU13P_UG.pdf

## DDR4 同 SLR 200MHz 差分参考时钟，原理图第 3 页
## 原理图网络名为 C1_DDR4_CLKREF_P=AF32、C1_DDR4_CLKREF_N=AF33，位于 FPGA_BANK63
set_property -dict {PACKAGE_PIN AF32 IOSTANDARD LVDS} [get_ports BADJ_CLK_clk_p]
set_property -dict {PACKAGE_PIN AF33 IOSTANDARD LVDS} [get_ports BADJ_CLK_clk_n]
create_clock -period 5.000 -name C1_DDR4_CLKREF_200M [get_ports BADJ_CLK_clk_p]

## DDR4 SODIMM，数据位宽 64bit，使用 PL_DDR4_DQ[0:63] / DQS[0:7] / DM[0:7]
## AXVU13P datasheet 第 9-13 页；DDR4 A14/A15/A16 分别复用 WE_B/CAS_B/RAS_B
set_property PACKAGE_PIN AK31 [get_ports C0_DDR4_act_n]
set_property PACKAGE_PIN AC33 [get_ports {C0_DDR4_adr[0]}]
set_property PACKAGE_PIN AG29 [get_ports {C0_DDR4_adr[1]}]
set_property PACKAGE_PIN AJ29 [get_ports {C0_DDR4_adr[2]}]
set_property PACKAGE_PIN AG32 [get_ports {C0_DDR4_adr[3]}]
set_property PACKAGE_PIN AK28 [get_ports {C0_DDR4_adr[4]}]
set_property PACKAGE_PIN AJ30 [get_ports {C0_DDR4_adr[5]}]
set_property PACKAGE_PIN AG31 [get_ports {C0_DDR4_adr[6]}]
set_property PACKAGE_PIN AH31 [get_ports {C0_DDR4_adr[7]}]
set_property PACKAGE_PIN AG30 [get_ports {C0_DDR4_adr[8]}]
set_property PACKAGE_PIN AH32 [get_ports {C0_DDR4_adr[9]}]
set_property PACKAGE_PIN AJ27 [get_ports {C0_DDR4_adr[10]}]
set_property PACKAGE_PIN AJ31 [get_ports {C0_DDR4_adr[11]}]
set_property PACKAGE_PIN AF34 [get_ports {C0_DDR4_adr[12]}]
set_property PACKAGE_PIN AF30 [get_ports {C0_DDR4_adr[13]}]
set_property PACKAGE_PIN AE30 [get_ports {C0_DDR4_adr[14]}]
set_property PACKAGE_PIN AH29 [get_ports {C0_DDR4_adr[15]}]
set_property PACKAGE_PIN AJ28 [get_ports {C0_DDR4_adr[16]}]
set_property PACKAGE_PIN AH28 [get_ports {C0_DDR4_ba[0]}]
set_property PACKAGE_PIN AC32 [get_ports {C0_DDR4_ba[1]}]
set_property PACKAGE_PIN AH34 [get_ports {C0_DDR4_bg[0]}]
set_property PACKAGE_PIN AH33 [get_ports {C0_DDR4_bg[1]}]
set_property PACKAGE_PIN AE32 [get_ports {C0_DDR4_ck_c[0]}]
set_property PACKAGE_PIN AE31 [get_ports {C0_DDR4_ck_t[0]}]
set_property PACKAGE_PIN AJ33 [get_ports {C0_DDR4_cke[0]}]
set_property PACKAGE_PIN AC31 [get_ports {C0_DDR4_cs_n[0]}]
set_property PACKAGE_PIN BA34 [get_ports {C0_DDR4_dm_n[0]}]
set_property PACKAGE_PIN AT33 [get_ports {C0_DDR4_dm_n[1]}]
set_property PACKAGE_PIN BF39 [get_ports {C0_DDR4_dm_n[2]}]
set_property PACKAGE_PIN BC34 [get_ports {C0_DDR4_dm_n[3]}]
set_property PACKAGE_PIN BC31 [get_ports {C0_DDR4_dm_n[4]}]
set_property PACKAGE_PIN BF32 [get_ports {C0_DDR4_dm_n[5]}]
set_property PACKAGE_PIN AP31 [get_ports {C0_DDR4_dm_n[6]}]
set_property PACKAGE_PIN AW29 [get_ports {C0_DDR4_dm_n[7]}]
set_property PACKAGE_PIN AW34 [get_ports {C0_DDR4_dq[0]}]
set_property PACKAGE_PIN AW33 [get_ports {C0_DDR4_dq[1]}]
set_property PACKAGE_PIN AY36 [get_ports {C0_DDR4_dq[2]}]
set_property PACKAGE_PIN BA33 [get_ports {C0_DDR4_dq[3]}]
set_property PACKAGE_PIN AV33 [get_ports {C0_DDR4_dq[4]}]
set_property PACKAGE_PIN AY33 [get_ports {C0_DDR4_dq[5]}]
set_property PACKAGE_PIN AY35 [get_ports {C0_DDR4_dq[6]}]
set_property PACKAGE_PIN AV34 [get_ports {C0_DDR4_dq[7]}]
set_property PACKAGE_PIN AL32 [get_ports {C0_DDR4_dq[8]}]
set_property PACKAGE_PIN AM34 [get_ports {C0_DDR4_dq[9]}]
set_property PACKAGE_PIN AP33 [get_ports {C0_DDR4_dq[10]}]
set_property PACKAGE_PIN AM32 [get_ports {C0_DDR4_dq[11]}]
set_property PACKAGE_PIN AL34 [get_ports {C0_DDR4_dq[12]}]
set_property PACKAGE_PIN AN34 [get_ports {C0_DDR4_dq[13]}]
set_property PACKAGE_PIN AP34 [get_ports {C0_DDR4_dq[14]}]
set_property PACKAGE_PIN AR33 [get_ports {C0_DDR4_dq[15]}]
set_property PACKAGE_PIN BD39 [get_ports {C0_DDR4_dq[16]}]
set_property PACKAGE_PIN BE38 [get_ports {C0_DDR4_dq[17]}]
set_property PACKAGE_PIN BB38 [get_ports {C0_DDR4_dq[18]}]
set_property PACKAGE_PIN BF38 [get_ports {C0_DDR4_dq[19]}]
set_property PACKAGE_PIN BF37 [get_ports {C0_DDR4_dq[20]}]
set_property PACKAGE_PIN BC39 [get_ports {C0_DDR4_dq[21]}]
set_property PACKAGE_PIN BC38 [get_ports {C0_DDR4_dq[22]}]
set_property PACKAGE_PIN BE37 [get_ports {C0_DDR4_dq[23]}]
set_property PACKAGE_PIN BE36 [get_ports {C0_DDR4_dq[24]}]
set_property PACKAGE_PIN BD36 [get_ports {C0_DDR4_dq[25]}]
set_property PACKAGE_PIN BB35 [get_ports {C0_DDR4_dq[26]}]
set_property PACKAGE_PIN BE35 [get_ports {C0_DDR4_dq[27]}]
set_property PACKAGE_PIN BA35 [get_ports {C0_DDR4_dq[28]}]
set_property PACKAGE_PIN BB36 [get_ports {C0_DDR4_dq[29]}]
set_property PACKAGE_PIN BC36 [get_ports {C0_DDR4_dq[30]}]
set_property PACKAGE_PIN BD35 [get_ports {C0_DDR4_dq[31]}]
set_property PACKAGE_PIN BB31 [get_ports {C0_DDR4_dq[32]}]
set_property PACKAGE_PIN BA30 [get_ports {C0_DDR4_dq[33]}]
set_property PACKAGE_PIN AY30 [get_ports {C0_DDR4_dq[34]}]
set_property PACKAGE_PIN BA29 [get_ports {C0_DDR4_dq[35]}]
set_property PACKAGE_PIN AY32 [get_ports {C0_DDR4_dq[36]}]
set_property PACKAGE_PIN BB30 [get_ports {C0_DDR4_dq[37]}]
set_property PACKAGE_PIN AY31 [get_ports {C0_DDR4_dq[38]}]
set_property PACKAGE_PIN BB29 [get_ports {C0_DDR4_dq[39]}]
set_property PACKAGE_PIN BD29 [get_ports {C0_DDR4_dq[40]}]
set_property PACKAGE_PIN BE32 [get_ports {C0_DDR4_dq[41]}]
set_property PACKAGE_PIN BD33 [get_ports {C0_DDR4_dq[42]}]
set_property PACKAGE_PIN BE30 [get_ports {C0_DDR4_dq[43]}]
set_property PACKAGE_PIN BE31 [get_ports {C0_DDR4_dq[44]}]
set_property PACKAGE_PIN BE33 [get_ports {C0_DDR4_dq[45]}]
set_property PACKAGE_PIN BC29 [get_ports {C0_DDR4_dq[46]}]
set_property PACKAGE_PIN BF30 [get_ports {C0_DDR4_dq[47]}]
set_property PACKAGE_PIN AP30 [get_ports {C0_DDR4_dq[48]}]
set_property PACKAGE_PIN AP29 [get_ports {C0_DDR4_dq[49]}]
set_property PACKAGE_PIN AL30 [get_ports {C0_DDR4_dq[50]}]
set_property PACKAGE_PIN AM31 [get_ports {C0_DDR4_dq[51]}]
set_property PACKAGE_PIN AN31 [get_ports {C0_DDR4_dq[52]}]
set_property PACKAGE_PIN AR30 [get_ports {C0_DDR4_dq[53]}]
set_property PACKAGE_PIN AN29 [get_ports {C0_DDR4_dq[54]}]
set_property PACKAGE_PIN AL29 [get_ports {C0_DDR4_dq[55]}]
set_property PACKAGE_PIN AU32 [get_ports {C0_DDR4_dq[56]}]
set_property PACKAGE_PIN AW31 [get_ports {C0_DDR4_dq[57]}]
set_property PACKAGE_PIN AU30 [get_ports {C0_DDR4_dq[58]}]
set_property PACKAGE_PIN AT30 [get_ports {C0_DDR4_dq[59]}]
set_property PACKAGE_PIN AV32 [get_ports {C0_DDR4_dq[60]}]
set_property PACKAGE_PIN AV31 [get_ports {C0_DDR4_dq[61]}]
set_property PACKAGE_PIN AU31 [get_ports {C0_DDR4_dq[62]}]
set_property PACKAGE_PIN AT29 [get_ports {C0_DDR4_dq[63]}]
set_property PACKAGE_PIN AW36 [get_ports {C0_DDR4_dqs_c[0]}]
set_property PACKAGE_PIN AW35 [get_ports {C0_DDR4_dqs_t[0]}]
set_property PACKAGE_PIN AN33 [get_ports {C0_DDR4_dqs_c[1]}]
set_property PACKAGE_PIN AN32 [get_ports {C0_DDR4_dqs_t[1]}]
set_property PACKAGE_PIN BE40 [get_ports {C0_DDR4_dqs_c[2]}]
set_property PACKAGE_PIN BD40 [get_ports {C0_DDR4_dqs_t[2]}]
set_property PACKAGE_PIN BC37 [get_ports {C0_DDR4_dqs_c[3]}]
set_property PACKAGE_PIN BB37 [get_ports {C0_DDR4_dqs_t[3]}]
set_property PACKAGE_PIN BB32 [get_ports {C0_DDR4_dqs_c[4]}]
set_property PACKAGE_PIN BA32 [get_ports {C0_DDR4_dqs_t[4]}]
set_property PACKAGE_PIN BD31 [get_ports {C0_DDR4_dqs_c[5]}]
set_property PACKAGE_PIN BD30 [get_ports {C0_DDR4_dqs_t[5]}]
set_property PACKAGE_PIN AM30 [get_ports {C0_DDR4_dqs_c[6]}]
set_property PACKAGE_PIN AM29 [get_ports {C0_DDR4_dqs_t[6]}]
set_property PACKAGE_PIN AV29 [get_ports {C0_DDR4_dqs_c[7]}]
set_property PACKAGE_PIN AU29 [get_ports {C0_DDR4_dqs_t[7]}]
set_property PACKAGE_PIN AB32 [get_ports {C0_DDR4_odt[0]}]
set_property PACKAGE_PIN AJ34 [get_ports C0_DDR4_reset_n]

set_property IOSTANDARD SSTL12_DCI [get_ports {C0_DDR4_act_n C0_DDR4_adr[*] C0_DDR4_ba[*] C0_DDR4_bg[*] C0_DDR4_cke[*] C0_DDR4_cs_n[*] C0_DDR4_odt[*]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {C0_DDR4_ck_c[*] C0_DDR4_ck_t[*]}]
set_property IOSTANDARD POD12_DCI [get_ports {C0_DDR4_dm_n[*] C0_DDR4_dq[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {C0_DDR4_dqs_c[*] C0_DDR4_dqs_t[*]}]
set_property IOSTANDARD LVCMOS12 [get_ports C0_DDR4_reset_n]

## 用户复位按键，低有效，手册第 46 页；BF35 位于 Bank 62，原理图 VCCO_62 为 1.2V
set_property PACKAGE_PIN BF35 [get_ports sys_rstn]
set_property IOSTANDARD LVCMOS12 [get_ports sys_rstn]
set_property PULLUP true [get_ports sys_rstn]
set_false_path -from [get_ports sys_rstn]

## CP2102GM USB-UART，手册第 44 页
set_property PACKAGE_PIN BF25 [get_ports rx]
set_property PACKAGE_PIN BE25 [get_ports tx]
set_property IOSTANDARD LVCMOS18 [get_ports {rx tx}]

## C910 JTAG 调试口，接到 FMC1+ 子卡 J20 插针组
## J20-17 FMC管脚K17=HA_N_17 -> FMC1_HA17_CC_N=BA23 -> jtag_tclk
## J20-18 FMC管脚K16=HA_P_17 -> FMC1_HA17_CC_P=AY23 -> jtag_tms
## J20-19 FMC管脚J19=HA_N_18 -> FMC1_HA18_N=AP23 -> jtag_tdi
## J20-20 FMC管脚J18=HA_P_18 -> FMC1_HA18_P=AN23 -> jtag_tdo
## J20-21 FMC管脚H20=LA_N_15 -> FMC1_LA15_N=AM15 -> jtag_trstn
set_property PACKAGE_PIN AP23 [get_ports jtag_tdi]
set_property PACKAGE_PIN AY23 [get_ports jtag_tms]
set_property PACKAGE_PIN BA23 [get_ports jtag_tclk]
set_property PACKAGE_PIN AN23 [get_ports jtag_tdo]
set_property PACKAGE_PIN AM15 [get_ports jtag_trstn]
set_property IOSTANDARD LVCMOS18 [get_ports {jtag_tclk jtag_tms jtag_tdi jtag_tdo jtag_trstn}]
set_property PULLDOWN true [get_ports jtag_tclk]
set_property PULLUP true [get_ports {jtag_tms jtag_tdi jtag_trstn}]
set_property CLOCK_BUFFER_TYPE NONE [get_ports jtag_tclk]
create_clock -period 100.000 -name C910_JTAG_TCK [get_ports jtag_tclk]
set_clock_groups -asynchronous -group [get_clocks C910_JTAG_TCK] -group [get_clocks -include_generated_clocks C1_DDR4_CLKREF_200M]
set_false_path -from [get_ports jtag_trstn]
